### ISSUE TITLE
"num_sampled_nodes"报错

### ISSUE THREAD

**Issue by umsimonchen** [QwQ2000/TheWebConf24-LTGNN-PyTorch#2]
您好。
我在运行这个代码的时候报了这错，请问是哪里有问题吗？
求解答，谢谢。

![image](https://github.com/QwQ2000/TheWebConf24-LTGNN-PyTorch/assets/55136583/bfb7f358-3cc2-4ad1-8a05-1a2159650ab0)

**Comment by QwQ2000** [comment]
Thank you for your interest in our work! 🤗

Based on the error message you encountered, it seems that your `torch_geometric` and `pyg-lib` versions **differ from the tested environment of this code repository**. Specifically, the class `GlobalStorage` in your `torch_geometric` version does not have a `num_sampled_nodes` member, which is causing the error.

To resolve this issue, I think it might be helpful if you ensure that your Python library versions align with our official settings. Specifically, **use the following versions**:
- `torch_geometric==2.2.0` or `torch_geometric==2.3.1`
- `pyg-lib==0.2.0+pt113cu117` 

Remember that while `pyg-lib` is **optional** for running this code, it significantly accelerates the sampling process. We **highly recommend** installing this library. 

Feel free to ask any additional questions if you encounter further issues. We’re here to help! 🤝 
You can also refer to our previous answer in Issue #1 since it may provide additional insights.

**Comment by QwQ2000** [comment]
Besides, please be cautious with the global path variable `ROOT_PATH` defined in the file `code/world.py`. It would be advisable to update this path to match your local code folder path.

**Comment by umsimonchen** [comment]
Thank you very much! The program finally ran after installing the pyg-lib!
